server:
  port: 9002
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:users}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:codaglobal}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration/
  application:
    name: User
  rabbitmq:
    host: ${RABBIT_URL:localhost}
    port: 5672
    username: guest
    password: guest

spring.cloud.stream.bindings.output.destination: Orders
spring.cloud.stream.default.contentType: application/json

Order:
  ribbon:
    listOfServers: ${ORDER_SERVER_LIST:http://localhost:9001/}

