server:
  port: 9002
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_CONNECTION_STRING:jdbc:mysql://localhost:3306/users}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:codaglobal}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
  application:
    name: User
Order:
  ribbon:
    listOfServers: ${ORDER_SERVER_LIST:http://localhost:9001/}

